{
 "title": "dashboard-immo-grp2",
 "description": "dashboard de pro !\ngrp2 > grp1, grp3 et grp4",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Nombre de requêtes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"appli2\", handler!~\"/metrics|/healthcheck|none\"}) by (handler, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux d'erreur sur /predict",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"/predict\", job=\"appli2\", method=\"POST\", status!=\"2xx\"})/sum(http_requests_total{handler=\"/predict\", job=\"appli2\", method=\"POST\"})*100 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps d’inférence en ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(inference_time_ms_sum[5m]) / rate(inference_time_ms_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}